import * as types from '../constants/actions';
export const orderedEnough = () =>{return {type: types.ORDERED_ENOUGH}}
export const orderedNotEnough = () =>{return {type: types.ORDERED_NOT_ENOUGH}}
export const putCoin = () =>{return {type: types.PUT_COIN}}
export const useCoin = () =>{return {type: types.USE_COIN}}
export const orderArabica = () =>{return {type: types.ORDER_ARABICA}}
export const cancelArabica = () =>{return {type: types.CANCEL_ARABICA}}
export const orderRobusta = () =>{return {type: types.ORDER_ROBUSTA}}
export const cancelRobusta = () =>{return {type: types.CANCEL_ROBUSTA}}
export const orderCream = () =>{return {type: types.ORDER_CREAM}}
export const cancelCream = () =>{return {type: types.CANCEL_CREAM}}
export const orderPlasticCup = () =>{return {type: types.ORDER_PLASTIC_CUP}}
export const cancelPlasticCup = () =>{return {type: types.CANCEL_PLASTIC_CUP}}
export const orderPaperCup = () =>{return {type: types.ORDER_PAPER_CUP}}
export const cancelPaperCup = () =>{return {type: types.CANCEL_PAPER_CUP}}
export const lessSugar = () =>{return {type: types.LESS_SUGAR}}
export const moreSugar = () =>{return {type: types.MORE_SUGAR}}
export const start = () =>{return {type: types.START}}
export const stop = () =>{return {type: types.STOP}}
