const ADD_ARABICA = 'ADD_ARABICA';
const USE_ARABICA = 'USE_ARABICA';
const ADD_ARABUSTA = 'ADD_ARABUSTA';
const USE_ARABUSTA = 'USE_ARABUSTA';
const ADD_CREAM = 'ADD_CREAM';
const USE_CREAM = 'USE_CREAM';
const ADD_SUGAR = 'ADD_SUGAR';
const USE_SUGAR = 'USE_SUGAR';
const ADD_CUP_PLASTIC = 'ADD_CUP_PLASTIC';
const USE_CUP_PLASTIC = 'USE_CUP_PLASTIC';
const ADD_CUP_PAPER = 'ADD_CUP_PAPER';
const USE_CUP_PAPER = 'USE_CUP_PAPER';

const CHOOSE_COFFEE = 'CHOOSE_COFFEE';
const CHOOSE_CREAM = 'CHOOSE_CREAM';
const CHOOSE_SUGAR = 'CHOOSE_SUGAR';
const CHOOSE_CUP_CLASS = 'CHOOSE_CUP_CLASS';

const PUT_COIN = 'PUT_COIN';
const TAKE_CUP = 'TAKE_CUP';
const START = 'START';
const COUNT_DOWN = 'COUNT_DOWN';
